### ISSUE TITLE
Failing to compile with socket2 v0.3.10

### ISSUE THREAD

**Issue by andykilroy** [alexcrichton/socket2-rs#37]
Am finding a curious issue when running 'cargo build' on my application with socket2-rs v0.3.10.  When compiling my app, at the point where cargo is building the socket2-rs dependency cargo comes back with:

```
   Compiling socket2 v0.3.10
error: cannot find macro `__cfg_if_items!` in this scope
  --> /Users/akilroy/.cargo/registry/src/github.com-1ecc6299db9ec823/socket2-0.3.10/src/sys/unix.rs:27:1
   |
27 | / cfg_if::cfg_if! {
28 | |     if #[cfg(any(target_os = "dragonfly", target_os = "freebsd",
29 | |                  target_os = "ios", target_os = "macos",
30 | |                  target_os = "openbsd", target_os = "netbsd",
...  |
37 | |     }
38 | | }
   | |_^
   |
   = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)

[snipped, more errors below this]
```

The dependencies in my Cargo.toml:

```
[dependencies]
clap = "2.33"
socket2 = { version = "0.3.10", features = ["reuseport"] }
base64 = "0.10"
failure = "0.1"
exitfailure = "0.5"
structopt = "0.2"

```

When cloning the socket2-rs repository, checking out 0.3.10 and running 'cargo build --features reuseport'  there is no problem:

```
$ cargo clean ; cargo build
   Compiling libc v0.2.60
   Compiling cfg-if v0.1.9
   Compiling socket2 v0.3.10 (/Users/akilroy/workspace/dev/rust/socket2-rs)
    Finished dev [unoptimized + debuginfo] target(s) in 2.54s
```

**Comment by alexcrichton** [comment]
This is likely indicative of either your compiler or a dependency needs to be updated, but I don't think this is an issue with this crate.

**Comment by andykilroy** [comment]
Found it.  Was pulling in and aged cfg-if 0.1.2.  Thanks Alex!

**Comment by aleksuss** [comment]
I've had the same issue when I tried to publish my crate which has a dependency `socket2-0.3.11` with Rust 1.38. But with Rust 1.36 is OK.
Compile output:
```
error: cannot find macro `__cfg_if_items` in this scope
  --> /Users/crocus/.cargo/registry/src/github.com-1ecc6299db9ec823/socket2-0.3.11/src/sys/unix.rs:27:1
   |
27 | / cfg_if::cfg_if! {
28 | |     if #[cfg(any(target_os = "dragonfly", target_os = "freebsd",
29 | |                  target_os = "ios", target_os = "macos",
30 | |                  target_os = "openbsd", target_os = "netbsd",
...  |
37 | |     }
38 | | }
   | |_^
   |
   = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)

error: cannot find macro `__cfg_if_items` in this scope
  --> /Users/crocus/.cargo/registry/src/github.com-1ecc6299db9ec823/socket2-0.3.11/src/sys/unix.rs:40:1
   |
40 | / cfg_if::cfg_if! {
41 | |     if #[cfg(any(target_os = "linux", target_os = "android",
42 | |                  target_os = "dragonfly", target_os = "freebsd",
43 | |                  target_os = "openbsd", target_os = "netbsd",
...  |
48 | |     }
49 | | }
   | |_^
   |
   = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)

error: cannot find macro `__cfg_if_items` in this scope
  --> /Users/crocus/.cargo/registry/src/github.com-1ecc6299db9ec823/socket2-0.3.11/src/sys/unix.rs:51:1
   |
51 | / cfg_if::cfg_if! {
52 | |     if #[cfg(any(target_os = "macos", target_os = "ios"))] {
53 | |         use libc::TCP_KEEPALIVE as KEEPALIVE_OPTION;
54 | |     } else if #[cfg(any(target_os = "openbsd", target_os = "netbsd", target_os = "haiku"))] {
...  |
58 | |     }
59 | | }
   | |_^
   |
   = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)

error[E0425]: cannot find value `MSG_NOSIGNAL` in this scope
   --> /Users/crocus/.cargo/registry/src/github.com-1ecc6299db9ec823/socket2-0.3.11/src/sys/unix.rs:408:21
    |
408 |                     MSG_NOSIGNAL,
    |                     ^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find value `MSG_NOSIGNAL` in this scope
   --> /Users/crocus/.cargo/registry/src/github.com-1ecc6299db9ec823/socket2-0.3.11/src/sys/unix.rs:422:21
    |
422 |                     MSG_NOSIGNAL,
    |                     ^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find value `IPV6_ADD_MEMBERSHIP` in this scope
   --> /Users/crocus/.cargo/registry/src/github.com-1ecc6299db9ec823/socket2-0.3.11/src/sys/unix.rs:628:54
    |
628 |         unsafe { self.setsockopt(libc::IPPROTO_IPV6, IPV6_ADD_MEMBERSHIP, mreq) }
    |                                                      ^^^^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find value `IPV6_DROP_MEMBERSHIP` in this scope
   --> /Users/crocus/.cargo/registry/src/github.com-1ecc6299db9ec823/socket2-0.3.11/src/sys/unix.rs:647:54
    |
647 |         unsafe { self.setsockopt(libc::IPPROTO_IPV6, IPV6_DROP_MEMBERSHIP, mreq) }
    |                                                      ^^^^^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find value `KEEPALIVE_OPTION` in this scope
   --> /Users/crocus/.cargo/registry/src/github.com-1ecc6299db9ec823/socket2-0.3.11/src/sys/unix.rs:707:66
    |
707 |             let secs: c_int = self.getsockopt(libc::IPPROTO_TCP, KEEPALIVE_OPTION)?;
    |                                                                  ^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find value `KEEPALIVE_OPTION` in this scope
   --> /Users/crocus/.cargo/registry/src/github.com-1ecc6299db9ec823/socket2-0.3.11/src/sys/unix.rs:721:52
    |
721 |                 self.setsockopt(libc::IPPROTO_TCP, KEEPALIVE_OPTION, dur.as_secs() as c_int)?;
    |                                                    ^^^^^^^^^^^^^^^^ not found in this scope

error: aborting due to 9 previous errors

For more information about this error, try `rustc --explain E0425`.
error: could not compile `socket2`.
```
